name: CI

on:
  push:
    branches: [development, master]
  pull_request:
    branches: [development, master]
  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:
  ci:
    uses: AtyaLibraries/github-workflows/.github/workflows/dotnet-package-ci.yml@v1
    with:
      solution: ./Primitives.sln
      test-project: ./tests/Primitives.UnitTests/Primitives.UnitTests.csproj
      package-project: ./src/Primitives/Primitives.csproj
